name: Update Products

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "update products"
          git push
